wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703124830.601142
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
